sudo: false
language: python

python:
    - '2.7'
    - '3.5'

before_install:
    - pip install codecov

install:
    - pip install -e .[test]

script:
    - py.test --cov=zeep --cov-report=term-missing

after_success: 
    - codecov
