sudo: false
language: python
cache: pip

python:
    - '2.7'
    - '3.5'
    - 'pypy'

before_install:
    - pip install codecov

install:
    - pip install -e .[test]

script:
    - py.test --cov=zeep --cov-report=term-missing

after_success: 
    - codecov
