build: false  # Not a C# project, build stuff at the test step instead.
environment:
  matrix:
    - PYTHON_VERSION: "2.7"
      PYTHON : "C:\\Python27"
    - PYTHON_VERSION: "3.5"
      PYTHON: "C:\\Python35-x64"
    - PYTHON_VERSION: "3.6"
      PYTHON: "C:\\Python36-x64"
    - PYTHON_VERSION: "3.7"
      PYTHON: "C:\\Python37-x64"

install:
  - "%PYTHON%/Scripts/easy_install -U pip"
  - "%PYTHON%/Scripts/pip install wheel"
  - "%PYTHON%/Scripts/pip install --only-binary :all: lxml==4.2.5"
  - "%PYTHON%/Scripts/pip install -e .[test]"

test_script:
  - "%PYTHON%/Scripts/py.test --cov=zeep --cov-report=term-missing"

after_test:
  - "%PYTHON%/python setup.py bdist_wheel"
  - ps: "ls dist"

artifacts:
  - path: dist\*
